name: Express API

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-18.04


    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.12.1
        uses: actions/setup-node@v3
        with:
         node-version: 18.12.1
      - run: npm install
      - run: npm start
